# Generated by Django 3.2.2 on 2023-02-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycsvfile',
            name='report_id',
            field=models.CharField(default='abcd123456', max_length=10),
        ),
    ]
